# Algorithm for gcd

In [2]:
def gcd(a,b):
    if a<b:
        (a,b)=(b,a)
    if(a%b) ==0:
        return b
    else:
        return (gcd(b,a%b))

In [3]:
gcd(12,2)

2

# EXTENDED EUCLIDEAN ALGORITHM

# Key Generation Algorithm

In [4]:
import numpy as np
K = [1,1,0,0,0,1,1,1,0,0,1,0,1,1,0,0]
H = [3,5,2,0,4,1,6,7]

In [5]:
K1_11=K[:len(K)//2]
K2_11=K[len(K)//2:]
K1_11

[1, 1, 0, 0, 0, 1, 1, 1]

In [6]:
def key_generation3(K,H):
    K1_11=K[:len(K)//2]
    K2_11=K[len(K)//2:]
    H_K1_11=[K1_11[i] for i in H ]
    H_K2_11=[K2_11[i] for i in H ]
    K_1=np.bitwise_xor(np.bitwise_or(H_K1_11,K2_11),(K1_11))
    K_2= np.bitwise_xor(np.bitwise_and(H_K2_11,K1_11),(K2_11))   
    return K_1,K_2
key_generation3(K,H)

(array([1, 0, 1, 1, 1, 0, 0, 0], dtype=int32),
 array([0, 1, 1, 0, 1, 1, 0, 0], dtype=int32))

In [7]:
def step4(K,H):
    K1,K2=key_generation3(K,H)
    H_K1=[K1[i] for i in H ]
    H_K2=[K2[i] for i in H ]
    K1_11=np.bitwise_xor(np.bitwise_or(H_K2,K1),(K2))
    K2_11= np.bitwise_xor(np.bitwise_and(H_K1,K2),(K1)) 
    K1_1=list(K1_11[2:])+list(K1_11[:2])
    K2_1=list(K2_11[-3:])+list(K2_11[:-3])
    return K1_1,K2_1
step4(K,H)
    

([0, 1, 0, 0, 0, 0, 1, 0], [0, 0, 0, 1, 0, 0, 1, 0])

In [8]:
N=[1,1,0,0,0,1,1,1,0,1,0,0,1,1,1,0]
pie=['9','A','4','6','0','B','2','7','E','3','C','1','5','D','8','F']
P=[7,5,4,2,0,1,3,6]
K1,K2=step4(K,H)
def Cipher(N,pie,P):
    numerics = []
    alphabets = []
    for sub in pie:

        # checking and inserting in respective container
        if sub.isnumeric():
            numerics.append(sub)
        else:
            alphabets.append(sub)

    # attaching lists post sort
    res = sorted(numerics) + sorted(alphabets)
    dictionary = dict(zip(res, N))
    H=[dictionary[i] for i in pie ]
    
    G0=H[:len(H)//2]
    D0=H[len(H)//2:]
    P_G0=[G0[i] for i in P]
    D1=np.bitwise_xor(P_G0,K1)
    P_K1=[K1[i] for i in P]
    or1=np.bitwise_or(G0,P_K1)
    and1=np.bitwise_and(P_G0,K1)
    G_=np.bitwise_xor(D0,or1)
    G1=np.bitwise_xor(G_,and1)
    P_G1=[G1[i] for i in P]
    P_K2=[K2[i] for i in P]
    D2=np.bitwise_xor(P_G1,K2)
    G_o=np.bitwise_or(G1,P_K2)
    G_a=np.bitwise_and(P_G1,K2)
    G_2=np.bitwise_xor(D1,G_o)
    G2=np.bitwise_xor(G_2,G_a)
    return G2,D2
Cipher(N,pie,P)


(array([1, 1, 0, 1, 1, 0, 1, 1], dtype=int32),
 array([1, 0, 0, 0, 0, 0, 1, 1], dtype=int32))

In [12]:
G2,D2=(Cipher(N,pie,P))
C=list(G2)+list(D2)
C

[1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1]